# Generated by Django 4.2.11 on 2024-04-10 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Familia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_familia", models.CharField(max_length=300)),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Filho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_filho", models.CharField(max_length=300)),
                ("ponto", models.DecimalField(decimal_places=1, max_digits=10)),
                ("data_ponto", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Responsavel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_responsavel", models.CharField(max_length=300)),
                (
                    "nome_familia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pontos_app.familia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Responsavel_Filho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pontos_app.filho",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pontos_app.responsavel",
                    ),
                ),
            ],
        ),
    ]
