# Generated by Django 4.2.11 on 2024-09-18 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pontos_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=300)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("senha", models.CharField(max_length=64)),
                ("responsavel", models.BooleanField()),
                (
                    "nome_familia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pontos_app.familia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pontos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motivo", models.TextField()),
                ("quantidade", models.DecimalField(decimal_places=2, max_digits=5)),
                ("data_ponto", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "filho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pontos_app.pessoa",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="responsavel",
            name="nome_familia",
        ),
        migrations.RemoveField(
            model_name="responsavel_filho",
            name="filho",
        ),
        migrations.RemoveField(
            model_name="responsavel_filho",
            name="responsavel",
        ),
        migrations.DeleteModel(
            name="Filho",
        ),
        migrations.DeleteModel(
            name="Responsavel",
        ),
        migrations.DeleteModel(
            name="Responsavel_Filho",
        ),
    ]
