# Generated by Django 4.2.11 on 2024-09-18 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pontos_app", "0002_pessoa_pontos_remove_responsavel_nome_familia_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pontos",
            old_name="filho",
            new_name="responsavel",
        ),
    ]
