# Generated by Django 4.2.11 on 2024-09-18 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pontos_app", "0004_remove_pessoa_responsavel_responsavel_filho_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pessoa",
            old_name="nome_familia",
            new_name="familia",
        ),
    ]
