# Generated by Django 4.2.11 on 2024-09-18 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("pontos_app", "0005_rename_nome_familia_pessoa_familia"),
    ]

    operations = [
        migrations.AddField(
            model_name="pessoa",
            name="data_cadastro",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
