# Generated by Django 4.2.11 on 2024-09-18 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pontos_app", "0006_pessoa_data_cadastro"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="responsavel",
            name="pessoa",
        ),
        migrations.RemoveField(
            model_name="pontos",
            name="responsavel",
        ),
        migrations.AlterField(
            model_name="pontos",
            name="filho",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pontos_app.pessoa"
            ),
        ),
        migrations.DeleteModel(
            name="Filho",
        ),
        migrations.DeleteModel(
            name="Responsavel",
        ),
    ]
