# Generated by Django 4.2.11 on 2024-09-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pontos_app",
            "0007_remove_responsavel_pessoa_remove_pontos_responsavel_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pessoa",
            name="responsavel",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
